# Generated by Django 5.2.5 on 2025-08-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_available_book_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
